source "https://rubygems.org"
gem "cucumber", ">= 2.3.3"
gem "headless", ">= 2.2.3"
gem "page-object", ">= 1.1.1"
gem "parallel_tests",">= 2.5.0"
gem "rake", ">= 11.1.2"
gem "rspec", ">= 3.4.0"
gem "selenium-webdriver",">= 2.53.0"
gem "watir", :platforms => [:mswin, :mingw]
gem "watir-webdriver", ">= 0.9.1"
